---
- hosts: all
  become: yes
  tasks:
   - name: create Docker config directory
     file: path=/etc/docker state=directory

   - name: install Docker
     apt:
       name: containerd
       state: present
       update_cache: true

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: Add Kubernetes apt-key
     get_url:
       url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
       dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
       mode: "0644"
       force: true

   - name: Add Kubernetes APT repository
     apt_repository:
       repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
       state: present
       update_cache: yes

   - name: install kubelet
     apt:
       name: kubelet=1.31.1-1.1
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm=1.31.1-1.1
       state: present

- hosts: control_plane
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl=1.31.1-1.1
       state: present
       force: yes
